### ISSUE TITLE
elements navigation with plugin syntax

### ISSUE THREAD

**Issue by tranfuga25s** [junichi11/cakephp-netbeans#118]
When an tag $this->element('element') is found, doing Ctrl + click netbeas get's me to the corresponding element.
But if the element has the plugin syntax, ej: SomePlugin.element, the action does not work.

**Comment by junichi11** [comment]
Works for me.
![cakephp-netbeans-issue118](https://cloud.githubusercontent.com/assets/738383/7727655/20ca13c2-ff45-11e4-8df0-ecfbfe30ed79.png)
