### ISSUE TITLE
Custom www_root

### ISSUE THREAD

**Issue by thanat** [junichi11/cakephp-netbeans#120]
Hi, 
would it be possible to add field to the "custom directrory path" in porject properties -> Frameworks ->  CakePHP, where could i set the path to webroot, in case i have custom path to webroot ? attached is image for better explanation.

![custom-www_root](https://cloud.githubusercontent.com/assets/507885/6748774/d8f1c6c0-cee9-11e4-9917-c17b083f97d5.png)

**Comment by junichi11** [comment]
Did you try to set it to `Sources > Web Root`?

**Comment by thanat** [comment]
I've the Sources > Web Root set correctly. 
it would be handy to see the webroot in the list as i can see model/view.... as on my screenshot
i can still access the webroot clicking "sources->www_root"

**Comment by junichi11** [comment]
Sorry, I'm not sure what you mean yet. 
Do you want to add a webroot node to your project tree like Helper, View, ...?

**Comment by thanat** [comment]
yes, that is exactly what i mean. to have the webroot node in project tree like the Helper, View, Model....
on my screenshot its in red, because its not existing :)

**Comment by junichi11** [comment]
Did you try to check `Tools > Options > PHP > Framework & Tools > CakePHP > Node` ?

**Comment by thanat** [comment]
![screen shot 2015-03-20 at 14 35 02](https://cloud.githubusercontent.com/assets/507885/6752396/62146ff6-cf0e-11e4-8b84-b01d6e682cb9.png)

all is checked. the problem is my webroot folder is not called webroot. that why i sugested the "new" item in the project settings->Frameworks->CakePHP  custom direcgtory path.

**Comment by junichi11** [comment]
Fixed. 

Could you try to test it ?

https://github.com/junichi11/cakephp-netbeans/releases/tag/v0.12.3 (0.12.3.6-dev)

**Comment by thanat** [comment]
pefect, it works :)  :+1:   thanks for quick response and solution.

**Comment by junichi11** [comment]
You are welcome :)
