### ISSUE TITLE
Problem with PHP script

### ISSUE THREAD

**Issue by gmponos** [junichi11/cakephp-netbeans#121]
Hello,

I select to create a new PHP Project. I enter the Project name and the Sources folder according to the wizard. At the PHP Frameworks I choose the CakePHP project. At the options below I have checked the "Create database" field and the composer bullet with the empty option checked. In the "app name" I do not have a value. I press next and I do not select any other composer package. Then I receive the following error.

https://www.dropbox.com/s/cvoa8pbgubwynuj/Untitled.png?dl=0

I am sure that the path of the PHP script is the correct one. If I choose a Unzipping installation there is no problem occurred. Also I can't run the CakePHP commands.

Details:
Fedora release 21
PHP: 5.6.6
Netbeans: 8.0.2
Plugin: 0.12.3

Thanks in advance.

**Comment by junichi11** [comment]
Hi,

Thanks for reporting it! Sorry, this is a bug.
I'll fix it.

**Comment by junichi11** [comment]
Fixed.

Could you try to use the following version:
https://github.com/junichi11/cakephp-netbeans/releases/tag/v0.12.3 (0.12.3.7-dev)

Thanks.

**Comment by gmponos** [comment]
Thank you. It is fixed now.
