### ISSUE TITLE
How to set .cake path

### ISSUE THREAD

**Issue by minhcanhdn** [junichi11/cakephp-netbeans#127]
Dear author,

Could you help me how to set .cake path. I created a file with name shorcut.cake and I try to set path is: shorcut.cake or ../shortcut.cake. Both of them is not correct and display error: File name must be .cake

**Comment by junichi11** [comment]
Please try to change your file name from `shortcut.cake` to `.cake`.

**Comment by junichi11** [comment]
@minhcanhdn Did you resolve this? If no, please feel free to reopen this issue.
