### ISSUE TITLE
Netbeans - Codeception bugs

### ISSUE THREAD

**Issue by dynasource** [junichi11/cakephp-netbeans#129]
I know its the wrong topic, but cant find the correct one. 
I adopted your plugin of Netbeans-Codeception. Great work!
Before I had my own one using non-native NB by using CMD, but I liked your because of the support for 'run focussed test method'

Everything works find, except for the F5 or reload tests. When you reload after running one method, it looses this focus and runs the whole file. I would love to see this one fixed, if you have time of course. Perhabs its a small one. This is the functionality I am using most, so I would be of great value. 

thanx!

**Comment by junichi11** [comment]
Sorry. Don't submit that to this GitHub Issues.

Please submit that to NetBeans Bugzilla[1] (PHP/Codeception). I'll look at it.

[1] https://netbeans.org/community/issues.html

Thanks.

**Comment by dynasource** [comment]
did that, no response.

**Comment by junichi11** [comment]
Could you write the url?

**Comment by junichi11** [comment]
It seems that your issue is not submitted to NB Bugzilla...

**Comment by junichi11** [comment]
@dynasource I searched your issue in NetBeans Bugzilla. But I can't find it. So, if you know the URL, please write it. Otherwise, could you submit it there again? 

Thanks.

**Comment by dynasource** [comment]
https://netbeans.org/bugzilla/show_bug.cgi?id=254120

**Comment by dynasource** [comment]
its listed under PHPunit since Codeception was not available yet

**Comment by junichi11** [comment]
I see. I'll look at it.

Thanks!

**Comment by junichi11** [comment]
BTW, if you have a message for me, please use twitter[1] or contact form on my web site[2].

[1] https://twitter.com/junichi_11
[2] http://junichi11.com

Thanks for letting me know.

**Comment by dynasource** [comment]
I will from now, you may delete this issue. Thanks!
