### ISSUE TITLE
Can't select 2.x in the New Project Wizard

### ISSUE THREAD

**Issue by junichi11** [junichi11/cakephp-netbeans#130]
#### Reproducible steps:

1. New Project > PHP (PHP Application)
2. Go to PHP Framework 
3. Select CakePHP PHP Web Framework
4. Select Unzipping

#### Actual results:

There is no 2.x version.

#### Expected results:

There are 2.x versions.

**Comment by junichi11** [comment]
Fixed.

#### NOTE

If you can't get CakePHP verison numbers in the New Project Wizard:

- Please try checking whether your machine is connected to internet
- Your request count via GitHub API may be over the limit. Please try waiting for one hour.

**Comment by rjrincon** [comment]
Excellent thank you very much, works perfect.

**Comment by junichi11** [comment]
:+1:
