### ISSUE TITLE
cakephp 3 netbeans wrong folder structure

### ISSUE THREAD

**Issue by ermorela** [junichi11/cakephp-netbeans#131]
Hi I'm trying to run my first project with cakephp, using Netbeans 8.0.2 on MAC, with MAMP 3.4, installed the org-netbeans-modules-php-cake3-0.0.7-dev-201408251540.nbm. 
Looking at the nice tutorial available at https://www.youtube.com/watch?v=BFqhOmVoM5M, even if based on 2.x version, the directory structure that my IDE creates is completely different. Files like core.phh and database.php (and much more files and folders) are missing. In project properties Frameworks/CakePhp there's a warning: Not found cake script file(cake.php). Looking for the right files in cakephp-3.1.1 folder just downloaded it seems completely different than cakephp-2.7.5. Some suggestions? Thanks in advance

**Comment by junichi11** [comment]
What's the version number that you want to use?

> org-netbeans-modules-php-cake3-0.0.7-dev-201408251540.nbm.

You are using the plugin for CakePHP 3.x (cakephp**3**-netbeans). This repository(cakephp-netbeans) is for CakePHP1.x or 2.x.

**Comment by ermorela** [comment]
Yes I'm using cakephp-3.1.1
Netbeans 8.0.2 doesn't allow to create projects with earlier versions

**Comment by junichi11** [comment]
@ermorela 
> Netbeans 8.0.2 doesn't allow to create projects with earlier versions

Does it mean earlier versions of CakePHP3 (e.g. 3.0.x, 3.1.0)? If yes, you can set version number in composer.json.
I'm not sure what you want to do yet. Please exactly write that.

**Comment by junichi11** [comment]
If you have some issues for cakephp3-netbeans plugin, please submit them to the following:
https://github.com/junichi11/cakephp3-netbeans/issues

Thanks.

**Comment by ermorela** [comment]
OK moved to the right place. What I'm trying to do is in the first post. Thanks
