### ISSUE TITLE
Cannot load plugin with development version (netbeans 8.1dev version > 2016xxxx)

### ISSUE THREAD

**Issue by fdalex** [junichi11/cakephp-netbeans#134]
Hi, the cakephp (2) plugin won't load with development version of netbeans (NetBeans IDE Build 201605110002) : 
- if i try to activate the plugin :
"Activation failed: Not all requested modules can be enabled: [StandardModule:org.cakephp.netbeans jarFile: C:\...\AppData\Roaming\NetBeans\8.1\modules\org-cakephp-netbeans.jar]"

- if i uninstall the plugin and try to reinstall it : 
"Some plugins require plugin Editor Library 2 to be installed.
The plugin Editor Library 2 is requested in implementation version 44."

I tried to compile the plugin with the sources but it fails, looks like something is missing or not up to date, mainly i have this method "Expression className = node.getClassName();" with error "Cannot find symbol"

It would be nice if I could use your plugin on the most recent version of netbeans, I'm using php7 with cakephp 2.8.x and only the netbeans development version supports php7 syntaxes.

**Comment by fdalex** [comment]
Any news ? :)

**Comment by junichi11** [comment]
I'm sorry to be late. I would like to avoid to provide it as far as possible. Because I have to create it many times if some modules are updated. But I create it once. So please wait a little while.

Thanks.

**Comment by fdalex** [comment]
oki thank you ;)

**Comment by junichi11** [comment]
Done.
https://github.com/junichi11/cakephp-netbeans/releases/tag/v0.14.2

You should download the latest build version at least Build 20160530.
