### ISSUE TITLE
Can't install plugin to NetBeans 8.2

### ISSUE THREAD

**Issue by nojimage** [junichi11/cakephp-netbeans#135]
I tried install `org-cakephp-netbeans-0.14.2.1-dev.nbm` to NB8.2 (Build 201609300101).

But, I got this message, and can't install plugin.

![ss 2016-10-04 12 45 06](https://cloud.githubusercontent.com/assets/100564/19061969/6b8eed8e-8a30-11e6-848a-81259c43acf4.png)

Please tell me how to fix it.

**Comment by junichi11** [comment]
Thanks for reporting!
I'll fix it :)

**Comment by junichi11** [comment]
Fixed. https://github.com/junichi11/cakephp-netbeans/commit/8da7344d2055349427efb6594abdac75d5f38835

https://github.com/junichi11/cakephp-netbeans/releases/tag/v0.15.0

Thanks!
