### ISSUE TITLE
Cannot install plugin on Netbeans 12.2

### ISSUE THREAD

**Issue by carlosnb** [junichi11/cakephp-netbeans#142]
#### Issue type

- [] bug
- [x] enhancement

#### Overview description
Plugin cannot be installed on Netbeans 12.2

#### Steps to reproduce

1. Try to install plugin from 'Plugins' Netbeans menu.

#### Actual results
Some plugins require plugin PHP Editor to be installed.
The plugin PHP Editor is requested in implementation version 2.  
The following plugin is affected:       PHP CakePHP Framework
![Captura de pantalla de 2020-12-16 09-43-04](https://user-images.githubusercontent.com/5807630/102325224-2e995b00-3f83-11eb-9da9-cc6061c545da.png)

#### Expected results
Successfull installation

#### Your environment (NetBeans and plugin version, e.t.c.)
Netbeans 12.2 on Ubuntu 20.04
plugin 1.0.0

**Comment by junichi11** [comment]
@carlosnb Yes, I know it. I'll recreate a nbm later. Thanks!

**Comment by junichi11** [comment]
Fixed: Please give it a try: https://github.com/junichi11/cakephp-netbeans/releases/tag/v1.1.0
