### ISSUE TITLE
Go To Element

### ISSUE THREAD

**Issue by ighormartins** [junichi11/cakephp-netbeans#99]
When Ctrl Click an element on the View, if the Element doesn't exist it does nothing. Would be nice if it could create the element for me, like it does for the view.

E.G.
I write this line:
<?= $this->element('folder/subfolder/myelem') ?>
Then I Ctrl + click, and as it doesn't exist, it should create it, or at least popup asking if I want to create.

Would make programming easier.

**Comment by junichi11** [comment]
I'm so sorry to be late...

I've added it.
